# Generated by Django 4.1.7 on 2023-03-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('platform_id', models.CharField(max_length=20)),
                ('last_flag', models.DateTimeField()),
                ('toxicity', models.FloatField(default=0.5)),
                ('severe_toxicity', models.FloatField(default=0.5)),
                ('identity_attack', models.FloatField(default=0.5)),
                ('insult', models.FloatField(default=0.5)),
                ('threat', models.FloatField(default=0.5)),
                ('profanity', models.FloatField(default=0.5)),
                ('sexually_explicit', models.FloatField(default=0.5)),
                ('users', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('platform_id', models.CharField(max_length=20)),
                ('last_flag', models.DateTimeField()),
                ('toxicity', models.FloatField(default=0.5)),
                ('severe_toxicity', models.FloatField(default=0.5)),
                ('identity_attack', models.FloatField(default=0.5)),
                ('insult', models.FloatField(default=0.5)),
                ('threat', models.FloatField(default=0.5)),
                ('profanity', models.FloatField(default=0.5)),
                ('sexually_explicit', models.FloatField(default=0.5)),
                ('messages', models.PositiveBigIntegerField()),
                ('psycho_hazard', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
