# Generated by Django 4.1.7 on 2023-03-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServerProfile',
            new_name='CommunityProfile',
        ),
    ]
