# Generated by Django 4.1.7 on 2023-03-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_serverprofile_communityprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='messages',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
