# Generated by Django 4.1.7 on 2023-03-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_communityprofile_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='last_flag',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_flag',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
