# Generated by Django 4.1.7 on 2023-03-02 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_communityprofile_last_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='last_flag',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_flag',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
