# Generated by Django 4.1.7 on 2023-03-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_communityprofile_last_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='platform_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='platform_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
