# Generated by Django 4.1.7 on 2023-03-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_communityprofile_platform_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityprofile',
            name='identity_attack',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='insult',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='last_flag',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='profanity',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='severe_toxicity',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='sexually_explicit',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='threat',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='toxicity',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='users',
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.userprofile'),
        ),
    ]
