# Generated by Django 4.1.7 on 2023-03-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_communityprofile_identity_attack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='users',
            field=models.ManyToManyField(blank=True, to='profiles.userprofile'),
        ),
    ]
