# Generated by Django 4.1.7 on 2023-03-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_alter_membermanager_crime_coefficient_action_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membermanager',
            old_name='crime_coefficient_action',
            new_name='crime_coefficient_100_action',
        ),
        migrations.RemoveField(
            model_name='membermanager',
            name='crime_coefficient_trigger',
        ),
        migrations.RemoveField(
            model_name='messagemanager',
            name='crime_coefficient_action',
        ),
        migrations.RemoveField(
            model_name='messagemanager',
            name='crime_coefficient_trigger',
        ),
        migrations.AddField(
            model_name='membermanager',
            name='crime_coefficient_300_action',
            field=models.IntegerField(choices=[(0, 'Noop'), (1, 'Notify'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=4),
        ),
    ]
