# Generated by Django 4.1.7 on 2023-04-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="discord_log_channel",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="discord_notify_target",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
