# Generated by Django 4.1.7 on 2023-03-08 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychopass', '0002_alter_communitypsychopass_options_and_more'),
        ('dominator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dominator',
            new_name='MemberDominator',
        ),
        migrations.CreateModel(
            name='MessageDominator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_log_channel', models.CharField(blank=True, max_length=20, null=True)),
                ('discord_notify_target', models.CharField(blank=True, max_length=20, null=True)),
                ('toxicity_action', models.IntegerField(choices=[(0, 'Noop'), (1, 'Notify'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=1)),
                ('toxicity_trigger', models.FloatField(default=0.5)),
                ('severe_toxicity_action', models.IntegerField(choices=[(0, 'Noop'), (1, 'Notify'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=1)),
                ('severe_toxicity_trigger', models.FloatField(default=0.5)),
                ('identity_attack_action', models.IntegerField(choices=[(0, 'Noop'), (1, 'Notify'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=1)),
                ('identity_attack_trigger', models.FloatField(default=0.5)),
                ('insult_action', models.IntegerField(choices=[(0, 'Noop'), (1, 'Notify'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=1)),
                ('insult_trigger', models.FloatField(default=0.5)),
                ('threat_action', models.IntegerField(choices=[(0, 'Noop'), (1, 'Notify'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=1)),
                ('threat_trigger', models.FloatField(default=0.5)),
                ('profanity_action', models.IntegerField(choices=[(0, 'Noop'), (1, 'Notify'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=1)),
                ('profanity_trigger', models.FloatField(default=0.5)),
                ('sexually_explicit_action', models.IntegerField(choices=[(0, 'Noop'), (1, 'Notify'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=1)),
                ('sexually_explicit_trigger', models.FloatField(default=0.5)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='psychopass.communitypsychopass')),
            ],
        ),
    ]
