# Generated by Django 5.2.5 on 2025-08-08 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_initial'),
        ('dominator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDominator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_coefficient_100_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=0)),
                ('crime_coefficient_300_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=4)),
                ('toxicity_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=0)),
                ('toxicity_threshold', models.FloatField(default=0.5)),
                ('severe_toxicity_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=0)),
                ('severe_toxicity_threshold', models.FloatField(default=0.5)),
                ('identity_attack_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=0)),
                ('identity_attack_threshold', models.FloatField(default=0.5)),
                ('insult_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=0)),
                ('insult_threshold', models.FloatField(default=0.5)),
                ('threat_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=0)),
                ('threat_threshold', models.FloatField(default=0.5)),
                ('profanity_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=0)),
                ('profanity_threshold', models.FloatField(default=0.5)),
                ('sexually_explicit_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=0)),
                ('sexually_explicit_threshold', models.FloatField(default=0.5)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
            ],
            options={
                'verbose_name': 'Member Dominator',
                'verbose_name_plural': 'Member Dominators',
            },
        ),
        migrations.CreateModel(
            name='MessageDominator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toxicity_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=0)),
                ('toxicity_threshold', models.FloatField(default=0.5)),
                ('severe_toxicity_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=0)),
                ('severe_toxicity_threshold', models.FloatField(default=0.5)),
                ('identity_attack_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=0)),
                ('identity_attack_threshold', models.FloatField(default=0.5)),
                ('insult_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=0)),
                ('insult_threshold', models.FloatField(default=0.5)),
                ('threat_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=0)),
                ('threat_threshold', models.FloatField(default=0.5)),
                ('profanity_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=0)),
                ('profanity_threshold', models.FloatField(default=0.5)),
                ('sexually_explicit_action', models.IntegerField(choices=[(0, 'Notify'), (1, 'Remove'), (2, 'Mute'), (3, 'Kick'), (4, 'Ban')], default=0)),
                ('sexually_explicit_threshold', models.FloatField(default=0.5)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
            ],
            options={
                'verbose_name': 'Message Dominator',
                'verbose_name_plural': 'Message Dominators',
            },
        ),
    ]
