# Generated by Django 4.1.7 on 2023-03-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dominator', '0002_rename_dominator_memberdominator_messagedominator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberdominator',
            options={'verbose_name': 'Member Dominator', 'verbose_name_plural': 'Member Dominators'},
        ),
        migrations.AlterModelOptions(
            name='messagedominator',
            options={'verbose_name': 'Message Dominator', 'verbose_name_plural': 'Message Dominators'},
        ),
    ]
