# Generated by Django 4.1.7 on 2023-03-08 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPsychoPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('platform_id', models.CharField(max_length=20, unique=True)),
                ('last_flag', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('messages', models.PositiveBigIntegerField(default=0)),
                ('psycho_hazard', models.BooleanField(default=False)),
                ('toxicity', models.FloatField(default=0.5)),
                ('severe_toxicity', models.FloatField(default=0.5)),
                ('identity_attack', models.FloatField(default=0.5)),
                ('insult', models.FloatField(default=0.5)),
                ('threat', models.FloatField(default=0.5)),
                ('profanity', models.FloatField(default=0.5)),
                ('sexually_explicit', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPsychoPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('platform_id', models.CharField(max_length=20, unique=True)),
                ('users', models.ManyToManyField(blank=True, to='psychopass.userpsychopass')),
            ],
        ),
    ]
