# Generated by Django 4.1.7 on 2023-04-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychopass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpsychopass',
            name='last_flag',
        ),
    ]
