# Generated by Django 4.1.7 on 2023-03-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychopass', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitypsychopass',
            options={'verbose_name': 'Community Psycho-Pass', 'verbose_name_plural': 'Community Psycho-Passes'},
        ),
        migrations.AlterModelOptions(
            name='userpsychopass',
            options={'verbose_name': 'Psycho-Pass', 'verbose_name_plural': 'Psycho-Passes'},
        ),
    ]
