# Generated by Django 5.2.5 on 2025-08-08 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_initial'),
        ('psychopass', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPsychoPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('messages', models.PositiveIntegerField(db_default=0)),
                ('toxicity', models.FloatField(db_default=0.5)),
                ('severe_toxicity', models.FloatField(db_default=0.5)),
                ('identity_attack', models.FloatField(db_default=0.5)),
                ('insult', models.FloatField(db_default=0.5)),
                ('threat', models.FloatField(db_default=0.5)),
                ('profanity', models.FloatField(db_default=0.5)),
                ('sexually_explicit', models.FloatField(db_default=0.5)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Psycho-Pass',
                'verbose_name_plural': 'Psycho-Passes',
            },
        ),
        migrations.CreateModel(
            name='CommunityPsychoPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
                ('users', models.ManyToManyField(blank=True, to='psychopass.userpsychopass')),
            ],
            options={
                'verbose_name': 'Community Psycho-Pass',
                'verbose_name_plural': 'Community Psycho-Passes',
            },
        ),
    ]
