# Generated by Django 5.0.3 on 2024-03-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychopass', '0004_alter_userpsychopass_identity_attack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpsychopass',
            name='identity_attack',
            field=models.FloatField(db_default=0.5),
        ),
        migrations.AlterField(
            model_name='userpsychopass',
            name='insult',
            field=models.FloatField(db_default=0.5),
        ),
        migrations.AlterField(
            model_name='userpsychopass',
            name='messages',
            field=models.PositiveIntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name='userpsychopass',
            name='profanity',
            field=models.FloatField(db_default=0.5),
        ),
        migrations.AlterField(
            model_name='userpsychopass',
            name='psycho_hazard',
            field=models.BooleanField(db_default=False),
        ),
        migrations.AlterField(
            model_name='userpsychopass',
            name='severe_toxicity',
            field=models.FloatField(db_default=0.5),
        ),
        migrations.AlterField(
            model_name='userpsychopass',
            name='sexually_explicit',
            field=models.FloatField(db_default=0.5),
        ),
        migrations.AlterField(
            model_name='userpsychopass',
            name='threat',
            field=models.FloatField(db_default=0.5),
        ),
        migrations.AlterField(
            model_name='userpsychopass',
            name='toxicity',
            field=models.FloatField(db_default=0.5),
        ),
    ]
