# Generated by Django 5.0.6 on 2024-05-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psychopass", "0005_alter_userpsychopass_identity_attack_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpsychopass",
            name="psycho_hazard",
        ),
    ]
